### ISSUE TITLE
Change ENTITY_TYPE value from TEST to GENERIC

### ISSUE THREAD

**Issue by docktermj** [Senzing/ibm-openshift-guide#24]
See https://github.com/Senzing/docker-compose-demo/issues/112

**Comment by SamMacy** [comment]
No instance of SENZING_ENTITY_TYPE

**Comment by docktermj** [comment]
@SamMacy Need to re-open to fix this:

https://github.com/Senzing/openshift-demo/blob/967a8ba349eef1b86ee2756fa908254633576a7e/helm-values-templates/senzing-stream-loader-kafka.yaml#L21

**Comment by docktermj** [comment]
@SamMacy Need to re-open to fix:

https://github.com/Senzing/ibm-openshift-guide/blob/bd557b6896d58fa06dc0cf7dfdda63ae6c4cddcc/helm-values-templates/senzing-stream-loader-kafka.yaml#L21

https://github.com/Senzing/ibm-openshift-guide/blob/bd557b6896d58fa06dc0cf7dfdda63ae6c4cddcc/helm-values-templates/senzing-stream-loader-rabbitmq.yaml#L21
